### ISSUE TITLE
Inconsistent use of Passphrase and Password

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-declarative-onboarding#15]
When issuing a declaration to a remote device, the schema uses targetPassphrase, in the licensing schema the declaration uses bigIqPassword and bigIpPassword. Why the inconsistency? Which is appropriate? Password or Passphrase.

In the licensing schema we are given the ability to fetch a password from a URL, why is that not the case in targetPassphrase from the container?

**Comment by seattlevine** [comment]
It is targetPassphrase because that's what AS3 uses in its container schema. bigIqPassword/bigIpPassword because that was done earlier (before DO ran in a container) and is the typical terminology BIG-IP uses. When it came time to put DO in a container, I chose to be consistent with AS3 where the parameters are identical.
