### ISSUE TITLE
BIG-IQ Licensing Documentation needs more examples

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-declarative-onboarding#16]
The documentation for BIG-IQ licensing needs better examples.

We need an explicit example for each license pool type BIG-IQ support:

1. Purchased Pool
2. Registration Key (where you can specify the RegKey if you want)
3. Utility Pool

The example terms (words used to describe each pool attribute) MUST match the BIG-IQ documentation.

In addition, the section on non-routable declarations, where the BIG-IQ does not have a route to the BIG-IP, should describe the license interaction with a graphic diagram and why a hypervisor attribute is required.

**Comment by seattlevine** [comment]
Tracking with internal issue 246

**Comment by seattlevine** [comment]
DO supports registration key pools, but does not support allowing you to specify the registration key to use from that pool.

**Comment by seattlevine** [comment]
- DO does not currently support specifying the reg key to use from a reg key pool.
- Hypervisor is required for unreachable devices because it is required in [this API](https://clouddocs.f5.com/products/big-iq/mgmt-api/v6.1.0/HowToSamples/bigiq_public_api_wf/t_license_member_management.html?highlight=license#assigning-a-license-to-an-unreachable-device) and DO cannot guess the value for this.

**Comment by dstokesf5** [comment]
Examples of using BIG-IQ for licensing from a Declarative Onboarding declaration can be found here: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigiq-examples.html

If there is something missing from those examples, please open a new issue describing the specific piece that is missing.
