### ISSUE TITLE
DOv1.3.0 to create multiple vlans / self-ip need to run twice on v14.1 

### ISSUE THREAD

**Issue by pzolo** [F5Networks/f5-declarative-onboarding#32]
I want to create 5 vlan, no license, no hostname, nothing else: 

first attempt, only 1 VLAN was created: 

[root@localhost:NO LICENSE:Standalone] getDO # curl -s "localhost:8100/mgmt/shared/declarative-onboarding"  -u admin:a  -d @/config/vlan5 ;
{"result":{"class":"Result","code":202,"status":"RUNNING","message":"processing"},"declaration":{"schemaVersion":"1.3.0","class":"Device","async":true,"label":"vlan-only","Common":{"class":"Tenant","vlan1":{"class":"VLAN","tag":101,"interfaces":[{"name":"1.1","tagged":true}]},"vlan2":{"class":"VLAN","tag":102,"interfaces":[{"name":"1.1","tagged":true}]},"vlan3":{"class":"VLAN","tag":103,"interfaces":[{"name":"1.1","tagged":true}]},"vlan4":{"class":"VLAN","tag":104,"interfaces":[{"name":"1.1","tagged":true}]},"vlan5":{"class":"VLAN","tag":105,"interfaces":[{"name":"1.1","tagged":true}]}}}}[root@localhost:NO LICENSE:Standalone] getDO # #
[root@localhost:NO LICENSE:Standalone] getDO # # List vlans after first attempt
[root@localhost:NO LICENSE:Standalone] getDO # #
[root@localhost:NO LICENSE:Standalone] getDO # for i in {1..500} ; do echo "attempt: ${i}" ;  if [[ `curl -s "localhost:8100/mgmt/shared/declarative-onboarding"  -u admin:x  | jq .result.status` != '"RUNNING"' ]] ; then break ; fi   ; sleep 1 ;  done ; tmsh list net vlan one-line
attempt: 1
attempt: 2
attempt: 3
attempt: 4
attempt: 5
attempt: 6
attempt: 7
attempt: 8
net vlan vlan1 { fwd-mode l3 if-index 224 interfaces { 1.1 { tagged } } tag 101 }

Second attempt, the rest of the vlan are created 

[root@localhost:NO LICENSE:Standalone] getDO # curl -s "localhost:8100/mgmt/shared/declarative-onboarding"  -u admin:a  -d @/config/vlan5 ; for i in {1..500} ; do echo "attempt: ${i}" ;  if [[ `curl -s "localhost:8100/mgmt/shared/declarative-onboarding"  -u admin:x  | jq .result.status` != '"RUNNING"' ]] ; then break ; fi   ; sleep 1 ;  done ; tmsh list net vlan one-line;
attempt: 1
attempt: 2
attempt: 3
attempt: 4
attempt: 5
attempt: 6
attempt: 7
net vlan vlan1 { fwd-mode l3 if-index 224 interfaces { 1.1 { tagged } } tag 101 }
net vlan vlan2 { fwd-mode l3 if-index 256 interfaces { 1.1 { tagged } } tag 102 }
net vlan vlan3 { fwd-mode l3 if-index 240 interfaces { 1.1 { tagged } } tag 103 }
net vlan vlan4 { fwd-mode l3 if-index 288 interfaces { 1.1 { tagged } } tag 104 }
net vlan vlan5 { fwd-mode l3 if-index 272 interfaces { 1.1 { tagged } } tag 105 }

**Comment by seattlevine** [comment]
There is a subtle API change in 14.1 which was causing issues for DO. Prior to 14.1, when you query for an object for which there are no instances (query for VLANs when no VLANs exist, for example), the response looks like:
{
  "kind": "tm:net:vlan:vlancollectionstate",
  "selfLink": "https://localhost/mgmt/tm/net/vlan?ver=13.1.1"
}

When there are VLANs defined, they are in an array in the 'items' property. In 14+, when there are no instances, there is an items property with an empty array. This caused the raw type of object returned to DO by some lower level code to be different in this case (array vs object). This, in turn, caused DO to only create the first VLAN. On the subsequent POST, since at least one VLAN existed, DO was handling the declaration properly.

**Comment by seattlevine** [comment]
Fixed in 1.3.1
