### ISSUE TITLE
Multiple tasks support

### ISSUE THREAD

**Issue by zongzw** [F5Networks/f5-declarative-onboarding#34]
Hi, 

In Docker container running mode, POST `/mgmt/shared/declarative-onboarding` returns process status without any ID which can indicate the post-ed onboarding task. 

Is there any consideration of multiple tasks support. For example, there are 2 devices, and we are going to onboard the 2 devices in parallel, and check onboarding status via getting`/mgmt/shared/declarative-onboarding`.

**Comment by seattlevine** [comment]
Are you using DO 1.4.0? We added support for this scenario in that release.

**Comment by zongzw** [comment]
Thanks for that and I just verified the id can be used.
 
But I encountered one issue: 
When the targetHost is not reachable, the response keeps 202 processing, never changes although I set targetTimeout, it doesn't help. Is that an issue?

What's more, I want to learn some details about the onboarding process. 
1. When the target host is not ready(booting on the way, web server starting or so), will DO waiting for its readiness and then continue the onboarding?
2. When do-container responses with 200, does it mean everything on the onboarded bigip is ready to use, i.e. configuration done, provision done and license done, and thus can immediately deploy as3 configuration?
3. Sometimes, I encounter the situation of onboarding process report 500, but the onboarding partly success(license is done), that may be weird, and make bigip device's state out of control. Is that a rollback issue?

**Comment by seattlevine** [comment]
It should timeout eventually, but may take a long time (15 minutes or more). See number 1 below. targetTimeout is in the schema, but unfortunately not implemented in the code. I've created an internal issue to fix this.
1. It will wait for some time, but not forever.
2. Yes, once you get 200, DO is done. Provisioning and licensing are complete. Because of the way that BIG-IP reports status after licensing and provisioning (sometimes says it is Active and then goes to another state with no user action), we do see the BIG-IP prompt going through various stages after DO is complete. However, it should be ready for AS3 config at this time. If you find a case where this is not true, please file an issue.
3. DO tries to roll back things that make sense to roll back. However, we do not delete users or revoke licenses during rollback or any other time.

**Comment by zongzw** [comment]
Thanks for the clarification. @seattlevine
